// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA74mMcei9CCPq5y_aokllYBoj3M6W9w90',
    appId: '1:533938075764:web:5363a6c48694b6d603b921',
    messagingSenderId: '533938075764',
    projectId: 'synthesia-18dc7',
    authDomain: 'synthesia-18dc7.firebaseapp.com',
    storageBucket: 'synthesia-18dc7.firebasestorage.app',
    measurementId: 'G-NC0Q8WK4K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALQOM48dCY9odj8i7C52OtvYv_naoJ9BQ',
    appId: '1:533938075764:android:20a903715ee50d9903b921',
    messagingSenderId: '533938075764',
    projectId: 'synthesia-18dc7',
    storageBucket: 'synthesia-18dc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg10eREjmu3VavM_DxyL2Jb4OsIlB2rFE',
    appId: '1:533938075764:ios:d9e25ce6b37f5cec03b921',
    messagingSenderId: '533938075764',
    projectId: 'synthesia-18dc7',
    storageBucket: 'synthesia-18dc7.firebasestorage.app',
    iosBundleId: 'com.example.synthesia',
  );
}
